name: Tests
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15      
      - name: Check out source code
        uses: actions/checkout@v1
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false      
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .
      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v
      - name: TestResourceAttributes
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/spans/resattr
      - name: TestSpanContextPropagation
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/spans/ctxprop
      - name: TestSpanCapture
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/spans/capture
      - name: TestSpanEntryPoints
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/spans/entrypoints
      - name: TestSLOs
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/slo        
      - name: TestK8sCredentials
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/credentials/k8s
      - name: TestAWSCredentials
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/credentials/aws
      - name: TestAzureCredentials
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/credentials/azure
      - name: TestManagementZones
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/mgmz
      - name: TestAutoTags
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/autotags
      - name: TestAlerting
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/alerting
      - name: TestDashboards
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/dashboards
      - name: TestMaintenance
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/maintenance
      - name: TestRequestAttributes
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/requestattributes
      - name: TestCustomServices
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/customservices
      - name: TestNotifications
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/notifications
      - name: TestMetricEventAnomalies
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/anomalies/metrics
      - name: TestDiskEventAnomalies
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/anomalies/disks
      - name: TestApplicationAnomalies
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/anomalies/applications
      - name: TestDatabasesAnomalies
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/anomalies/databases
      - name: TestHostAnomalies
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/anomalies/hosts
      - name: TestServiceAnomalies
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/anomalies/services
      - name: TestCalculatedServiceMetrics
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/metrics/calculated/service
      - name: TestServiceNaming
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/naming/services
      - name: TestHostNaming
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/naming/hosts
      - name: TestProcessNaming
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/naming/processgroups

        